# Social Media Platform Backend

This repository includes basic REST template for Social Media Platform

## Features:
- Feed
- View post
- Edit post
- Add post
- Delete post
- Signup
- Login
- Logout

## Tools used
- `mongoose` - Library for NoSQL database MongoDB
- `bcrypt` - password encryption
- `multer` - file upload
- `JWT (JSON Web Token)` to authenticate REST requests
